apiVersion: v1
kind: Secret
metadata:
  name: comfyui-api-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  RUNPOD_API_KEY: {{ .Values.runpod.apiKey | quote }}
  RUNPOD_ENDPOINT_ID: {{ .Values.runpod.endpointId | quote }}
  COMFYUI_TIMEOUT: {{ .Values.runpod.timeout | quote }}
